# Generated by Django 4.1.3 on 2022-12-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postv_delete_post_alter_profile_bio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostV',
            new_name='Posts',
        ),
    ]
