# Generated by Django 4.1.3 on 2022-12-30 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='image',
        ),
    ]
