# Generated by Django 4.1.3 on 2022-12-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_posts_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='id_post',
        ),
    ]
