# Generated by Django 4.1.3 on 2022-12-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_posts_id_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
