# Generated by Django 4.1.3 on 2023-01-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
